import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getHeader, getFooter, strapiMediaURL } from "@/lib/strapi";
import Navbar from "@/components/shared/Navbar";
import Footer from '@/components/shared/Footer';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const hd = await getHeader();
  const ft = await getFooter();
  const [navLink, logo, logoUrl] = [hd.data.header.MainNav.navlink, hd.data.header.logo, strapiMediaURL(hd.data.header.logo.imageSrc.url)];
  const [footerLogo, copyright, socials, subscribe] = [ft.data.footer.smallLogo, ft.data.footer.copyright, ft.data.footer.socials, ft.data.footer.subscribe]
  return (
    <html lang="en">
      <body
        className="min-h-screen bg-[var(--mycelium-white)] font-sans antialiased"

      >
        <Navbar nav={navLink} logo={logo} logoUrl={logoUrl} />
        {children}
        <Footer
          footerLogo={footerLogo}
          copyright={copyright}
          socials={socials}
          subscribe={subscribe}
        />

      </body>
    </html>
  );
}
